DROP DATABASE IF EXISTS hack;
CREATE DATABASE hack;
USE hack;
DROP TABLE IF EXISTS DonationItems,DonationDates,DonationRoutes,Route, ItemTypes, DonorEmail, DonorAddress, DonorPhone, Donation,Donor;
CREATE TABLE Donor
(
donorID INT UNSIGNED AUTO_INCREMENT NOT NULL,
fName VARCHAR(50) NOT NULL,
lName VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY(donorID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
CREATE INDEX Donor_fName ON Donor(fName);
CREATE INDEX Donor_lName ON Donor(lName);
CREATE INDEX Donor_email ON Donor(email);

CREATE TABLE DonorAddress
(
donorID INT UNSIGNED NOT NULL,
address VARCHAR(255) NOT NULL,
city VARCHAR(50) NOT NULL,
state VARCHAR(2) NOT NULL,
zip varchar(20),
status INT DEFAULT 1,
FOREIGN KEY (donorID) REFERENCES donor(donorID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE DonorPhone
(
donorID INT UNSIGNED NOT NULL,
phone VARCHAR(20),
type VARCHAR(1) DEFAULT "C",
status INT DEFAULT 1,
createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
FOREIGN KEY (donorID) REFERENCES donor(donorID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
CREATE INDEX DonorPhone_phone ON DonorPhone(phone);

CREATE TABLE Donation
(
donorID INT UNSIGNED NOT NULL,
donationID INT UNSIGNED AUTO_INCREMENT NOT NULL,
dateEntered TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
status INT DEFAULT 0,
adminnotes VARCHAR(4000),
PRIMARY KEY(donationID),
FOREIGN KEY (donorID) REFERENCES Donor(donorID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE DonationDates
(
donationID INT UNSIGNED NOT NULL,
pickUpDate DATE NOT NULL,
FOREIGN KEY (donationID) REFERENCES Donation(donationID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE Route
(
routeID INT UNSIGNED NOT NULL AUTO_INCREMENT,
scheduleDate DATE NOT NULL,
dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY(routeID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE donationRoutes
(
donationID INT UNSIGNED NOT NULL,
routeID INT UNSIGNED NOT NULL,
position INT UNSIGNED NOT NULL,
FOREIGN KEY (donationID) REFERENCES Donation(donationID),
FOREIGN KEY (routeID) REFERENCES Route(routeID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE ItemTypes
(
itemTypeID INT UNSIGNED NOT NULL,
itemType VARCHAR(4000),
PRIMARY KEY(itemTypeID)
)ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE DonationItems
(
donationID INT UNSIGNED NOT NULL,
itemTypeID INT UNSIGNED NOT NULL,
itemcount INT UNSIGNED NOT NULL,
description VARCHAR(4000),
FOREIGN KEY (itemTypeID) REFERENCES ItemTypes(itemTypeID),
FOREIGN KEY (donationID) REFERENCES Donation(donationID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE DonationPictures
(
donationID INT UNSIGNED NOT NULL,
imageURL VARCHAR(500) NOT NULL,
FOREIGN KEY (donationID) REFERENCES Donation(donationID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;